Repository PacificEMIS/Pacific-SIS, pull requests merged in 2022-02, with the labels that each got.

#10 Dashboard rollover issue fixed
  UI/src/app/pages/dashboards/dashboard-analytics/dashboard-analytics.component.ts
Labels: Development Done

#18 PopulateFinalGrading API Modify.
  API/opensis.data/Repository/StaffPortalGradebookRepository.cs
Labels: API

#13 School Info Update/Submit button letter bug fixed
  UI/src/app/pages/school/add-school/general-info/general-info.component.html
Labels: Resolved

#34 Modified report api
  API/opensis.report/report.data/Repository/AttendanceReportRepository.cs
  API/opensis.report/report.data/Repository/ScheduleReportRepository.cs
  API/opensis.report/report.data/ViewModels/ScheduleReport/StudentScheduledListModel.cs
Labels: API

#39 some changes
  UI/src/app/models/attendance-code.model.ts
  UI/src/app/pages/courses/course-catalog/course-catalog.component.html
  UI/src/app/pages/courses/course-catalog/course-catalog.component.ts
  UI/src/app/pages/reports/attendance/attendance-report/attendance-report.component.html
  UI/src/app/pages/reports/attendance/attendance-report/attendance-report.component.ts
  UI/src/app/pages/shared/shared-function.ts
  UI/src/app/services/attendance-code.service.ts
Labels: Angular

#40 Weight Percentage showing issue fixed in Gradebook Grades
  UI/src/app/pages/class/grades/gradebook-grades/gradebook-grade-details/gradebook-grade-details.component.html
  UI/src/app/pages/class/grades/gradebook-grades/gradebook-grade-details/gradebook-grade-details.component.ts
  UI/src/app/pages/class/grades/gradebook-grades/gradebook-grades.component.html
  UI/src/app/pages/class/grades/gradebook-grades/gradebook-grades.component.ts
  UI/src/app/pages/staff/teacher-function/gradebook-grades/gradebook-grade-details/gradebook-grade-details.component.html
  UI/src/app/pages/staff/teacher-function/gradebook-grades/gradebook-grade-details/gradebook-grade-details.component.ts
  UI/src/app/pages/staff/teacher-function/gradebook-grades/gradebook-grade-list/gradebook-grade-list.component.html
  UI/src/app/pages/staff/teacher-function/gradebook-grades/gradebook-grade-list/gradebook-grade-list.component.ts
Labels: Angular

#42 modification in AddUpdateStudentFinalGrade , GetMarkingPeriodsByCourseSection, GetReportCardForStudents APIs
  API/opensis.data/Repository/InputFinalGradeRepository.cs
  API/opensis.data/Repository/MarkingperiodRepository.cs
  API/opensis.data/Repository/ReportCardRepository.cs
  API/opensis.data/ViewModels/MarkingPeriods/MarkingPeriodsByCourseSectionViewModel.cs
Labels: API

#44 B#929&#930 fsm
  API/opensis.data/Repository/MarkingperiodRepository.cs
  API/opensis.data/Repository/ReportCardRepository.cs
Labels: API

#45 Super Admin & Teacher >> Preferences bug fixed
  UI/src/@vex/layout/sidenav/sidenav.component.html
  UI/src/@vex/layout/sidenav/sidenav.component.ts
Labels: Angular

#46 Reports - Scheduling - Class Lists Report implemented
  UI/src/app/models/report.model.ts
  UI/src/app/pages/reports/schedule/class-list/class-list.component.html
  UI/src/app/pages/reports/schedule/class-list/class-list.component.scss
  UI/src/app/pages/reports/schedule/class-list/class-list.component.ts
  UI/src/app/services/report.service.ts
  UI/src/assets/i18n/en.json
  UI/src/assets/i18n/es.json
  UI/src/assets/i18n/fr.json
Labels: Angular

#47 Modification in GradebookGrade APIs.
  API/opensis.data/Repository/StaffPortalGradebookRepository.cs
  API/opensis.data/Repository/UserRepository.cs
  API/opensis.data/ViewModels/StaffPortalGradebook/GradebookGradeListViewModel.cs
Labels: API

#49 Gradebook Grades due date showing issue fixed, add notice issue fixed, Class lists report minor issues fixed and Super admin is not able to edit their own name issue fixed
  UI/src/app/pages/class/grades/gradebook-grades/gradebook-grades.component.html
  UI/src/app/pages/reports/schedule/class-list/class-list.component.ts
  UI/src/app/pages/school/notices/edit-notice/edit-notice.component.ts
  UI/src/app/pages/staff/add-staff/staff-addressinfo/staff-addressinfo.component.ts
  UI/src/app/pages/staff/add-staff/staff-certificationinfo/staff-certificationinfo.component.ts
  UI/src/app/pages/staff/add-staff/staff-generalinfo/staff-generalinfo.component.ts
  UI/src/app/pages/staff/add-staff/staff-schoolinfo/staff-schoolinfo.component.ts
  UI/src/app/pages/staff/teacher-function/gradebook-grades/gradebook-grade-list/gradebook-grade-list.component.html
Labels: Angular

#50 Admin - Grades - Add/Edit Historical Grades bug fixed
  UI/src/app/models/historical-marking-period.model.ts
  UI/src/app/pages/grades/administration/administration.component.html
  UI/src/app/pages/grades/administration/historical-grades-details/historical-grades-details.component.html
  UI/src/app/pages/grades/administration/historical-grades-details/historical-grades-details.component.scss
  UI/src/app/pages/grades/administration/historical-grades-details/historical-grades-details.component.ts
  UI/src/assets/i18n/en.json
  UI/src/assets/i18n/es.json
  UI/src/assets/i18n/fr.json
Labels: Angular

#57 Modification in AddGradebookGrade, AddGradebookGradeByStudent
  API/opensis.data/Repository/StaffPortalGradebookRepository.cs
Labels: API

#56 Staff Reports menu done.
  API/opensisAPI/Controllers/TestController.cs
  API/opensisAPI/RolePermission.json
Labels: API

#54 Dd#1406 fsm
  API/opensis.data/Repository/UserRepository.cs
  API/opensis.data/ViewModels/User/LoginViewModel.cs
Labels: API

#55 Teacher - Grades - msg for change in gradebook configuration - bug fixed
  UI/src/app/pages/class/grades/gradebook-grades/gradebook-grades.component.ts
  UI/src/app/pages/class/grades/grades.component.html
  UI/src/app/pages/class/grades/grades.component.ts
  UI/src/assets/i18n/en.json
  UI/src/assets/i18n/es.json
  UI/src/assets/i18n/fr.json
Labels: Angular

#58 Admin - notice - breadcrum header issue fixed
  UI/src/app/pages/school/notices/notices.component.html
Labels: Angular

#60 some fix
  UI/src/app/pages/scheduling/teacher-view-schedule/teacher-view-schedule.component.ts
  UI/src/app/pages/staff/teacher-function/input-final-grade/grade-details/grade-details.component.ts
Labels: Angular

#59 D#1342 rmi
  API/opensis.report/report.data/Repository/AttendanceReportRepository.cs
  API/opensis.report/report.data/ViewModels/AttendanceReport/StudentAttendanceReport.cs
Labels: API

#63 student menu added with RolePermission.
  API/opensisAPI/Category.json
  API/opensisAPI/Controllers/TestController.cs
  API/opensisAPI/Group.json
  API/opensisAPI/RolePermission.json
  API/opensisAPI/SubCategory.json
Labels: API

#66 Attendance Report implemented
  UI/src/app/pages/reports/attendance/attendance-report/attendance-report.component.html
  UI/src/app/pages/reports/attendance/attendance-report/attendance-report.component.ts
  UI/src/app/pages/scheduling/teacher-view-schedule/teacher-view-schedule.component.ts
  UI/src/app/pages/staff/teacher-function/input-final-grade/grade-details/grade-details.component.ts
Labels: Angular

#69 Enhancement done
  UI/src/app/common/default-values.service.ts
  UI/src/app/models/calendar-event.model.ts
  UI/src/app/pages/grades/report-cards/report-cards.component.html
  UI/src/app/pages/grades/report-cards/report-cards.component.ts
  UI/src/app/pages/school/calendar/add-calendar/add-calendar.component.html
  UI/src/app/pages/school/calendar/add-calendar/add-calendar.component.ts
  UI/src/app/pages/school/calendar/calendar.component.html
  UI/src/app/pages/school/calendar/calendar.component.ts
  UI/src/assets/i18n/en.json
  UI/src/assets/i18n/es.json
  UI/src/assets/i18n/fr.json
Labels: Angular

#70 ValidateUserLogin API modify
  API/opensis.data/Repository/UserRepository.cs
Labels: API

#71 Admin - Settings/Grade - Report Card Comment spelling bug fixed
  UI/src/assets/i18n/en.json
  UI/src/assets/i18n/es.json
  UI/src/assets/i18n/fr.json
Labels: Angular

#76 some changes
  UI/src/app/pages/attendance/add-absences/add-absences.component.html
  UI/src/app/pages/attendance/administration/administration.component.html
  UI/src/app/pages/attendance/attendance-codes/attendance-codes.component.html
  UI/src/app/pages/grades/administration/administration.component.html
  UI/src/app/pages/grades/effort-grade-scale/effort-grade-scale.component.html
  UI/src/app/pages/grades/historical-marking-periods/historical-marking-periods.component.ts
  UI/src/app/pages/grades/report-card-grades/report-card-grades.component.html
  UI/src/app/pages/grades/report-cards/report-cards.component.html
  UI/src/app/pages/grades/school-specific-standards/school-specific-standards.component.html
  UI/src/app/pages/grades/standard-grades/standard-grades.component.html
  UI/src/app/pages/grades/us-common-core-standards/us-common-core-standards.component.html
  UI/src/app/pages/list-of-values/school-classification/school-classification.component.html
  UI/src/app/pages/reports/attendance/attendance-report/attendance-report.component.html
  UI/src/app/pages/reports/attendance/average-daily-attendance/average-daily-attendance.component.html
  UI/src/app/pages/reports/schedule/add-drop-report/add-drop-report.component.html
  UI/src/app/pages/reports/school-report/institute-report/institute-report.component.html
  UI/src/app/pages/reports/staff-report/advance-report/advance-report.component.html
  UI/src/app/pages/reports/student-report/add-drop-report/add-drop-report.component.html
  UI/src/app/pages/reports/student-report/advance-report/advance-report.component.html
  UI/src/app/pages/reports/student-report/contact-info-report/contact-info-report.component.html
  UI/src/app/pages/reports/student-report/enrollment-report/enrollment-report.component.html
  UI/src/app/pages/reports/student-report/print-student-info/print-student-info.component.html
  UI/src/app/pages/school/periods/periods.component.html
  UI/src/app/pages/school/school-fields/school-fields.component.html
  UI/src/app/pages/school/sections/sections.component.html
  UI/src/app/pages/staff/staff-fields/staff-fields.component.html
  UI/src/app/pages/student/enrollment-codes/enrollment-codes.component.html
  UI/src/app/pages/student/student-fields/student-fields.component.html
  UI/src/app/pages/student/student-re-enroll/student-re-enroll.component.html
  UI/src/app/pages/tools/access-log/access-log.component.html
Labels: Angular

#73 B#923 fsm
  API/opensis.data/Repository/MarkingperiodRepository.cs
Labels: API

#78 StaffScheduleViewForCourseSection API Modify
  API/opensis.data/Repository/StaffScheduleRepository.cs
Labels: API

#77 some changes
  UI/src/app/pages/grades/historical-marking-periods/historical-marking-periods.component.ts
Labels: Angular

#79 Admin - Grades/Administration - space after comma & snackbar bug fixed
  UI/src/app/pages/grades/administration/administration.component.html
  UI/src/app/pages/grades/administration/historical-grades-details/historical-grades-details.component.ts
Labels: Angular

#81 Modification in GetAllSchools API
  API/opensis.data/Repository/SchoolRepository.cs
  API/opensis.data/Repository/StaffRepository.cs
  API/opensis.data/ViewModels/School/GetSchoolForView.cs
  API/opensis.data/ViewModels/School/SchoolListModel.cs
Labels: API

#84 initial dev done
  UI/src/@vex/layout/toolbar/select-bar/select-bar.component.ts
  UI/src/app/models/get-all-school.model.ts
  UI/src/app/pages/staff/add-staff/staff-schoolinfo/staff-schoolinfo.component.html
  UI/src/app/pages/staff/add-staff/staff-schoolinfo/staff-schoolinfo.component.ts
Labels: Angular

#88 B-904, B-963, B-971 issues fixed
  UI/src/app/app.component.ts
  UI/src/app/pages/staff/teacher-function/missing-attendance/missing-attendance.component.ts
  UI/src/app/pages/student/add-student/student-enrollmentinfo/student-enrollmentinfo.component.html
  UI/src/app/pages/student/add-student/student-enrollmentinfo/student-enrollmentinfo.component.ts
Labels: Angular

#90 Some Fix
  UI/src/@vex/layout/toolbar/select-bar/select-bar.component.ts
  UI/src/app/models/staff.model.ts
  UI/src/app/pages/attendance/teacher-missing-attendance/take-attendance/take-attendance.component.ts
  UI/src/app/pages/auth/login/login.component.ts
  UI/src/app/pages/staff/add-staff/staff-schoolinfo/staff-schoolinfo.component.ts
Labels: Angular

#92 Modification in ValidateUserLogin API
  API/opensis.data/Repository/UserRepository.cs
Labels: API

#97 GetGradebookGradeinFinalGrade API Modify
  API/opensis.data/Repository/InputFinalGradeRepository.cs
Labels: API

#95 GroupDropForScheduledStudent API Modify
  API/opensis.data/Repository/StudentScheduleRepository.cs
Labels: API

#94 Parent Menu added
  API/opensisAPI/Controllers/TestController.cs
  API/opensisAPI/Group.json
  API/opensisAPI/RolePermission.json
Labels: API

#93 some fix
  UI/src/app/pages/auth/login/login.component.ts
Labels: Angular

#99 Some validation added
  UI/src/app/models/student-final-grade.model.ts
  UI/src/app/pages/class/assignments/create-assignment/create-assignment.component.html
  UI/src/app/pages/class/assignments/create-assignment/create-assignment.component.ts
  UI/src/app/pages/class/grades/input-final-grades/input-final-grades.component.html
  UI/src/app/pages/class/grades/input-final-grades/input-final-grades.component.ts
  UI/src/app/pages/grades/transcripts/transcripts.component.html
  UI/src/app/pages/grades/transcripts/transcripts.component.scss
  UI/src/app/pages/grades/transcripts/transcripts.component.ts
  UI/src/app/pages/school/calendar/add-calendar/add-calendar.component.html
  UI/src/app/pages/school/calendar/add-calendar/add-calendar.component.ts
  UI/src/app/pages/school/marking-periods/edit-marking-period/edit-marking-period.component.html
  UI/src/app/pages/school/marking-periods/edit-marking-period/edit-marking-period.component.ts
  UI/src/app/pages/staff/teacher-function/gradebook-grades/gradebook-grade-list/gradebook-grade-list.component.ts
  UI/src/app/pages/staff/teacher-function/input-final-grade/grade-details/grade-details.component.html
  UI/src/app/pages/staff/teacher-function/input-final-grade/grade-details/grade-details.component.ts
Labels: Angular

#100 Admin-Dashboard showing old calendar events-bug fixed
  UI/src/app/pages/dashboards/dashboard-analytics/dashboard-analytics.component.ts
Labels: Angular

#101 some fix
  UI/src/app/pages/reports/attendance/attendance-report/attendance-report.component.ts
Labels: Angular

#109 Transcript work done
  UI/src/app/pages/student/add-student/student-transcript/student-transcript.component.html
  UI/src/app/pages/student/add-student/student-transcript/student-transcript.component.ts
Labels: Angular

#108 modification in ViewStaffSchoolInfo & GetAllStaffCertificateInfo API
  API/opensis.data/Repository/StaffRepository.cs
  API/opensis.data/ViewModels/Staff/StaffCertificateInfoListModel.cs
  API/opensis.data/ViewModels/Staff/StaffSchoolInfoAddViewModel.cs
Labels: API

#107 StaffListForMissingAttendance API modify
  API/opensis.data/Repository/StudentAttendanceRepository.cs
Labels: API

#96 Change in GetMarkingPeriodsByCourseSection API.
  API/opensis.data/Repository/MarkingperiodRepository.cs
Labels: API

#105 B#990 fsm
  API/opensis.report/report.data/Repository/AttendanceReportRepository.cs
Labels: API

#103 Admin - Tools - Options after rollover should NOT work - issue fixed
  UI/src/app/pages/staff/staff-data-import/staff-data-import.component.html
  UI/src/app/pages/staff/staff-data-import/staff-data-import.component.ts
  UI/src/app/pages/student/student-data-import/student-data-import.component.html
  UI/src/app/pages/student/student-data-import/student-data-import.component.ts
  UI/src/app/pages/tools/rollover/rollover.component.html
  UI/src/app/pages/tools/rollover/rollover.component.ts
  UI/src/assets/i18n/en.json
  UI/src/assets/i18n/es.json
  UI/src/assets/i18n/fr.json
Labels: Angular

#110 Teacher portal Class Lists report issue fixed and Report cards generate button issue fixed
  UI/src/app/pages/reports/schedule/class-list/class-list.component.html
  UI/src/app/pages/reports/schedule/class-list/class-list.component.ts
  UI/src/app/pages/student/add-student/student-report-card/student-report-card.component.html
  UI/src/assets/i18n/en.json
  UI/src/assets/i18n/es.json
  UI/src/assets/i18n/fr.json
Labels: Angular

#112 Issue fixed
  UI/src/app/pages/class/course-overview/course-overview.component.html
Labels: Angular

#113 API for Student Progress Report
  API/opensis.report/report.core/Student/Interfaces/IStudentReportService.cs
  API/opensis.report/report.core/Student/Services/StudentReportService.cs
  API/opensis.report/report.data/Interface/IStudentReportRepository.cs
  API/opensis.report/report.data/Repository/StudentReportRepository.cs
  API/opensis.report/report.data/ViewModels/StudentReport/StudentProgressReport.cs
  API/opensisAPI/Controllers/ReportController.cs
Labels: API
